remote_theme: "mmistakes/minimal-mistakes@4.24.0"
collections:
  publications:
    output: true
    permalink: /:collection/:path
plugins: [jekyll-include-cache]

defaults:
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true

sidebar:
  - title: "Title"
    image: http://placehold.it/350x250
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."