remote_theme: "mmistakes/minimal-mistakes@4.24.0"
collections:
  publications:
    permalink: /:collection/:path
plugins: [jekyll-include-cache]

defaults:
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: false
      share: true